/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS
DE SIGUIENTES EXPRESIONES: EJERCICIO DE CLASE

NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS
ASIGNATURA:PROGRAMACION l*/
# incluye  < iostream >
usando el  espacio de nombres  std;
int  main()
{
	return  0;
}