/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS
DE SIGUIENTES EXPRESIONES: EJERCICIO DE CLASE
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
using namespace std;
int
main()
{
	return 0;
  
